ToDoList/Models/ServiceLocator.cs
using Microsoft.Extensions.DependencyInjection;
using ToDoList.Dto.Factories;
using ToDoList.Infrastructure;
using ToDoList.Models.TaskLists;
using ToDoList.Models.Tasks;

namespace ToDoList.Models
{
    public static class ServiceLocator
    {
        public static void RegisterServices(IServiceCollection services)
        {
            services.AddTransient(typeof(IRepository<>), typeof(Repository<>));
            services.AddTransient<TaskService>();
            services.AddTransient<TaskListService>();
            services.AddSingleton<TaskFactory>();
            services.AddSingleton<TaskListFactory>();
        }
    }
}

ToDoList/Models/TaskLists/TaskList.cs
using System.Collections.Generic;
using ToDoList.Models.Tasks;

namespace ToDoList.Models.TaskLists
{
    public class TaskList
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public virtual ICollection<Task> Tasks { get; set; } = new List<Task>();
    }
}

ToDoList/Models/TaskLists/TaskListService.cs
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using ToDoList.Infrastructure;
using Task = ToDoList.Models.Tasks.Task;


namespace ToDoList.Models.TaskLists
{
    public class TaskListService
    {
        private readonly IRepository<TaskList> _repository;

        public TaskListService(IRepository<TaskList> repository)
        {
            _repository = repository;
        }
        
        public async System.Threading.Tasks.Task<TaskList> GetByIdAsync(int id)
        {
            return await _repository.SearchNoTrackingAsync(l=>l.Id==id).FirstAsync();
        }
        
        public async System.Threading.Tasks.Task<List<TaskList>> GetAllListsAsync()
        {
            return await _repository.GetAllNoTrackingAsync().ToListAsync();
        }

        public async System.Threading.Tasks.Task AddAsync(TaskList list)
        {
            _repository.Insert(list);
            await _repository.SaveChangesAsync();
        }

        public async System.Threading.Tasks.Task<bool> IsListExistAsync(int id)
        {
            return await _repository.AnyAsync(t => t.Id == id);
        }

        public async System.Threading.Tasks.Task DeleteByIdAsync(int id)
        {
            _repository.DeleteById(id);
            await _repository.SaveChangesAsync();
        }
    }
}

ToDoList/Models/Tasks/Task.cs
using System;
using ToDoList.Models.TaskLists;
using System.ComponentModel.DataAnnotations;

namespace ToDoList.Models.Tasks
{
    public class Task
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public DateTime CreationDate { get; set; }
        public bool IsCompleted { get; set; }
        public int? TaskListId { get; set; }

        public virtual TaskList TaskList { get; set; }
    }
}

ToDoList/Models/Tasks/TaskService.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using ToDoList.Infrastructure;
using Task = ToDoList.Models.Tasks.Task;

namespace ToDoList.Models.Tasks
{
    public class TaskService
    {
        private readonly IRepository<Task> _repository;

        public TaskService(IRepository<Task> repository)
        {
            _repository = repository;
        }

        public async System.Threading.Tasks.Task<List<Task>> GetTasksByListIdAsync(int? id)
        {
            return await _repository
                .SearchNoTrackingAsync(t => t.TaskListId == id)
                .OrderBy(t => t.IsCompleted)
                .ThenBy(t=>t.CreationDate)
                .ToListAsync();
        }

        public async System.Threading.Tasks.Task AddAsync(Task task)
        {
            _repository.Insert(task);
            await _repository.SaveChangesAsync();
        }

        public async System.Threading.Tasks.Task DeleteByIdAsync(int id)
        {
            _repository.DeleteById(id);
            await _repository.SaveChangesAsync();
        }

        public async System.Threading.Tasks.Task<bool> IsTaskExistAsync(int id)
        {
            return await _repository.AnyAsync(t => t.Id == id);
        }

        public async System.Threading.Tasks.Task UpdateAsync(Task entity)
        {
            _repository.Update(entity);
            await _repository.SaveChangesAsync();
        }
    }
}

ToDoList/Models/Tasks/TaskStatus.cs
namespace ToDoList.Models.Tasks
{
    public enum TaskStatus
    {
        Pending = 0,
        Completed = 1
    }
}

ToDoList/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using ToDoList.Dto;
using ToDoList.Models;
using Task = ToDoList.Models.Tasks.Task;
using TaskStatus = ToDoList.Models.Tasks.TaskStatus;

namespace ToDoList.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

ToDoList/Controllers/TaskListsController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ToDoList.Dto;
using ToDoList.Dto.Factories;
using ToDoList.Models.TaskLists;
using ToDoList.Models.Tasks;

namespace ToDoList.Controllers
{
    public class TaskListsController : Controller
    {
        private readonly TaskListService _taskListService;
        private readonly TaskService _taskService;
        private readonly TaskListFactory _factory;

        public TaskListsController(
            TaskListService taskListService,
            TaskService taskService,
            TaskListFactory factory)
        {
            _taskListService = taskListService;
            _taskService = taskService;
            _factory = factory;
        }

        [HttpGet]
        public async Task<IActionResult> GetTaskLists()
        {
            var taskLists = await _taskListService.GetAllListsAsync(); 
            return View(taskLists);
        }

        [HttpPost]
        public async Task<IActionResult> AddTaskList(TaskListDto dto)
        {
            var taskList = _factory.FromDto(dto);
            await _taskListService.AddAsync(taskList);
            return RedirectToAction("GetTaskLists");
        }

        [HttpGet]
        public async Task<IActionResult> GetTasksByListId(int id)
        {
            var tasks = await _taskService.GetTasksByListIdAsync(id);
            return View(tasks);
        }


        [HttpPost]
        public async Task<IActionResult> DeleteList(int id)
        {
            if (!await _taskListService.IsListExistAsync(id)) return NotFound();
            await _taskListService.DeleteByIdAsync(id);
            return RedirectToAction("GetTaskLists");
        }
    }
}

ToDoList/Controllers/TasksController.cs
// using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ToDoList.Dto;
using ToDoList.Models.Tasks;
using TaskFactory = ToDoList.Dto.Factories.TaskFactory;

namespace ToDoList.Controllers
{
    public class TasksController : Controller
    {
        private readonly TaskService _service;
        private readonly TaskFactory _factory;

        public TasksController(
            TaskService service,
            TaskFactory factory)
        {
            _service = service;
            _factory = factory;
        }

        public async Task<IActionResult> GetTasks()
        {
            var tasks = await _service.GetTasksByListIdAsync(null);
            return View(tasks);
        }

        [HttpPost]
        public async Task<IActionResult> AddTask(TaskDto dto)
        {
            var task = _factory.FromDto(dto);
            await _service.AddAsync(task);
            return RedirectToAction("GetTasks");
        }

        [HttpPost]
        public async Task<IActionResult> AddTaskInCurrentList(int listId, TaskDto dto)
        {
            var task = _factory.FromDto(dto);
            await _service.AddAsync(task);
            return RedirectToAction("GetTasksByListId", "TaskLists", new {id = listId});
        }

        [HttpPost]
        public async Task<IActionResult> DeleteTask(int id)
        {
            if (!await _service.IsTaskExistAsync(id)) return NotFound();
            await _service.DeleteByIdAsync(id);
            return RedirectToAction("GetTasks");
        }

        [HttpPost]
        public async Task<IActionResult> EditTask(TaskEditDto dto)
        {
            var task = _factory.FromDto(dto);
            await _service.UpdateAsync(task);
            return dto.TaskListId != null
                ? RedirectToAction("GetTasksByListId", "TaskLists", new {id = dto.Id})
                : RedirectToAction("GetTasks");
        }
    }
}

ToDoList/Views/Home/Index.cshtml
@model IEnumerable<ToDoList.Models.Tasks.Task>
@{
    Layout = null;
}
 
<!DOCTYPE html>
 
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>To Do List</title>
</head>
<body>
<a href="/Tasks/GetTasks">All tasks</a><br>
<a href="/TaskLists/GetTaskLists">All lists</a>
</body>
</html>

ToDoList/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoList</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ToDoList</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @* <li class="nav-item"> *@
                        @*     <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
                        @* </li> *@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        @* <div class="container"> *@
        @*     &copy; 2021 - ToDoList - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
        @* </div> *@
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ToDoList/Views/TaskLists/AddTaskList.cshtml
<form asp-controller="TaskLists" asp-action="AddTaskList">
    <input type="text" name="Name"/>
    <input type="submit" value="Save"/>
</form>

ToDoList/Views/TaskLists/EditTask.cshtml
@model ToDoList.Models.Tasks.Task

@using (Html.BeginForm("EditTask", "Tasks", FormMethod.Post))
{
    @Html.HiddenFor(t => t.Id)
    @Html.HiddenFor(t => t.TaskListId)
    @Html.EditorFor(t => t.IsCompleted)
    @Html.EditorFor(t => t.Description)
    <p>
        <input type="submit" value="Update"/>
    </p>
}

ToDoList/Views/TaskLists/GetTaskLists.cshtml
@model IEnumerable<ToDoList.Models.TaskLists.TaskList>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <title>To Do List</title>
</head>
<body>
<a asp-controller="Home" asp-action="Index">Back</a>
<div>
    <h3>Your Lists:</h3>
    <table>
        @foreach (var list in Model)
        {
            <tr>
                <td>
                    <p>
                        <a asp-controller="TaskLists" asp-action="GetTasksByListId" asp-route-id="@list.Id">@list.Name</a>
                    </p>
                </td>
                <td>
                    <form asp-controller="TaskLists" asp-action="DeleteList" asp-route-id="@list.Id">
                        <input type="submit" value="Delete">
                    </form>
                </td>
                @* <td><form method="post" action="/Home/DeleteTask"> *@
                @*     <input type="submit" value="Delete"> *@
                @* </form></td> *@
                @* <td><p><a href="/Home/Buy/@b.Id">Купить</a></p></td> *@
            </tr>
        }
    </table>
    @await Html.PartialAsync("AddTaskList")
</div>
</body>
</html>

ToDoList/Views/TaskLists/GetTasksByListId.cshtml
@model IEnumerable<ToDoList.Models.Tasks.Task>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>Something list</title>
</head>
<body>
<a asp-controller="TaskLists" asp-action="GetTaskLists">Back</a>
<div>
    
        @foreach (var t in Model)
        {
            <p>
                @await Html.PartialAsync("EditTask", t)//delete copy edit task?
                <form asp-controller="Tasks" asp-action="DeleteTask" asp-route-id="@t.Id">
                    <input type="submit" value="Delete">
                </form>      
            </p>
            
        }

    <form asp-controller="Tasks" asp-action="AddTaskInCurrentList" asp-route-listId="6">
        <input type="text" name="Description">
        <input type="submit" value="Save">
    </form>
</div>
</body>
</html>

ToDoList/Views/Tasks/AddTask.cshtml
<form asp-controller="Tasks" asp-action="AddTask">
    <input type="text" name="Description" />
    <input type="submit" value="Save" />
</form>

ToDoList/Views/Tasks/EditTask.cshtml
@model ToDoList.Models.Tasks.Task
@using (Html.BeginForm("EditTask", "Tasks", FormMethod.Post))
{
    @Html.HiddenFor(t => t.Id)
    @Html.EditorFor(t => t.IsCompleted)
    @Html.EditorFor(t => t.Description)
    <p>
        <input type="submit" value="Update"/>
    </p>
}

ToDoList/Views/Tasks/GetTasks.cshtml
@model IEnumerable<ToDoList.Models.Tasks.Task>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <title>To Do List</title>
</head>
<body>
<a asp-controller="Home" asp-action="Index">Back</a>
<div>
    <h3>Your Tasks:</h3>

    @foreach (var t in Model)
    {
        <p>
            @await Html.PartialAsync("EditTask", t)
                    <form asp-controller="Tasks" asp-action="DeleteTask" asp-route-id="@t.Id">
                        <input type="submit" value="Delete">
                    </form>      
        </p>
        
    }
    @await Html.PartialAsync("AddTask")
</div>
</body>
</html>